function safeHtml(html){const t=document.createElement("template");t.innerHTML=String(html||"");t.content.querySelectorAll("script,iframe,object,embed,link,meta,style").forEach(n=>n.remove());t.content.querySelectorAll("*").forEach(el=>{[...el.attributes].forEach(at=>{const n=at.name.toLowerCase(),v=at.value.trim().toLowerCase();if(n.startsWith("on")||n==="srcdoc"||((n==="href"||n==="src")&&v.startsWith("javascript:")))el.removeAttribute(at.name)})});return t.innerHTML}
function verdictIcon(v){return v==='conviene'?'✓':v==='non_conviene'?'!':'≈'}
function coverMarkup(p){return p.coverUrl?`<img class="analysis-cover-image" src="${esc(p.coverUrl)}" alt="${esc(p.title)}" loading="eager">`:`<div class="analysis-cover-fallback ${p.visual}"><span>${esc(p.emoji)}</span></div>`}
function renderSections(list){return list.map(s=>`<section class="analysis-section"><h2>${esc(s.title||s.section_key||'Sezione')}</h2><div class="analysis-copy">${s.content?safeHtml(s.content):''}</div></section>`).join('')}
document.addEventListener("DOMContentLoaded",async()=>{
 const host=document.getElementById("analysisHost"),slug=new URLSearchParams(location.search).get("slug");
 if(!slug){host.innerHTML='<div class="notice">Analisi non specificata</div>';return}
 try{
  const p=await BizScanData.fetchAnalysisBySlug(slug);if(!p){host.innerHTML='<div class="notice">Analisi non trovata</div>';return}
  document.title=p.title+' · BizScan';
  const [access,sections]=await Promise.all([BizScanData.hasAccess(p.id).catch(()=>false),BizScanData.fetchSections(p.id).catch(()=>[])]);
  const freeSections=sections.filter(s=>s.is_free===true),pdf=(p.attachments||[]).find(a=>a.type==='pdf');
  host.innerHTML=`<article class="analysis-shell"><div class="analysis-back"><button type="button" onclick="history.length>1?history.back():location.href='index.html'">←</button><span>Analisi BizScan</span></div><section class="analysis-product"><div class="analysis-media">${coverMarkup(p)}<span class="analysis-category">${esc(p.category||'BizScan')}</span></div><div class="analysis-intro"><div class="kicker">ANALISI COMPLETA</div><h1>${esc(p.title)}</h1><p>${esc(p.summary)}</p><div class="analysis-verdict"><span>${verdictIcon(p.verdict)}</span><div><small>Verdetto BizScan</small><strong>${esc(p.verdictLabel)}</strong></div></div><div class="analysis-metrics"><div><small>Investimento</small><strong>${esc(p.investment||'—')}</strong></div><div><small>Rischio</small><strong>${esc(p.riskLabel||'—')}</strong></div><div><small>Rientro</small><strong>${esc(p.payback||'—')}</strong></div><div><small>BizScan Score</small><strong>${p.score}/100</strong></div></div><div class="analysis-cta">${access?(pdf?'<button class="btn primary full" id="openPdf">Apri il PDF completo</button>':'<div class="notice">Accesso completo attivo</div>'):`<button class="btn primary full" onclick="openBuy('${p.slug}')">Sblocca analisi · ${p.price.toFixed(2).replace('.',',')} €</button><a class="btn dark full" href="pricing.html">Vedi tutti i piani</a>`}</div></div></section><div class="analysis-content" id="premiumContent"></div></article>`;
  const premium=document.getElementById('premiumContent');
  if(access){premium.innerHTML=sections.length?renderSections(sections):'<div class="notice">Accesso attivo. Il contenuto sarà visibile quando le sezioni verranno pubblicate.</div>';if(pdf)document.getElementById('openPdf').onclick=async()=>{try{window.open(await BizScanData.signedAttachmentUrl(pdf),'_blank','noopener')}catch(e){alert('Impossibile aprire il PDF')}}}
  else premium.innerHTML=(freeSections.length?renderSections(freeSections):'')+`<section class="analysis-lock"><div class="analysis-lock-icon">🔒</div><h2>Contenuto completo bloccato</h2><p>Costi dettagliati, rischi, errori, strategie e checklist operativa.</p><button class="btn primary" onclick="openBuy('${p.slug}')">Sblocca a ${p.price.toFixed(2).replace('.',',')} €</button><a href="pricing.html">Oppure scegli un pacchetto</a></section>`;
 }catch(e){console.error(e);host.innerHTML='<div class="notice">Impossibile caricare l’analisi</div>'}
});
